# Generated by Django 4.1 on 2023-10-08 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(upload_to='Category')),
                ('slug', models.SlugField(help_text='Slug is a field in autocomplete mode, but if you want you can modify its contents', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('specification', models.TextField(blank=True, default='')),
                ('price', models.FloatField(default=0.0, help_text='Price Can not be Less than Zero.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('inStock', models.BooleanField(default=True)),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('warranty', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='store.brand')),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='store.category')),
            ],
            options={
                'unique_together': {('name', 'category', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
